"""updatedduty table

Revision ID: 55e6d94f4ef4
Revises: e3655b9bda5d
Create Date: 2026-05-21 10:35:08.792862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e6d94f4ef4'
down_revision: Union[str, Sequence[str], None] = 'e3655b9bda5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_calculations', sa.Column('origin_country', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('destination_country', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('shipment_mode', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('incoterm', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('customs_clearance_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('port_charge', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('cif_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('bcd_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('bcd_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('igst_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('vat_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('sws_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('sws_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('anti_dumping_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('anti_dumping_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('safeguard_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('safeguard_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('trade_agreement', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('exemption_type', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('reduced_duty_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('compliance_status', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('compliance_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('duty_calculations', sa.Column('restricted_flag', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('prohibited_flag', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('missing_documents', sa.Text(), nullable=True))
    op.add_column('duty_calculations', sa.Column('customs_hold_status', sa.String(), nullable=True))
    op.add_column('duty_calculations', sa.Column('hold_reason', sa.Text(), nullable=True))
    op.add_column('duty_calculations', sa.Column('ai_recommendation', sa.Text(), nullable=True))
    op.add_column('duty_calculations', sa.Column('customs_notes', sa.Text(), nullable=True))
    op.add_column('duty_calculations', sa.Column('effective_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duty_calculations', 'effective_date')
    op.drop_column('duty_calculations', 'customs_notes')
    op.drop_column('duty_calculations', 'ai_recommendation')
    op.drop_column('duty_calculations', 'hold_reason')
    op.drop_column('duty_calculations', 'customs_hold_status')
    op.drop_column('duty_calculations', 'missing_documents')
    op.drop_column('duty_calculations', 'prohibited_flag')
    op.drop_column('duty_calculations', 'restricted_flag')
    op.drop_column('duty_calculations', 'compliance_score')
    op.drop_column('duty_calculations', 'compliance_status')
    op.drop_column('duty_calculations', 'reduced_duty_percent')
    op.drop_column('duty_calculations', 'exemption_type')
    op.drop_column('duty_calculations', 'trade_agreement')
    op.drop_column('duty_calculations', 'safeguard_amount')
    op.drop_column('duty_calculations', 'safeguard_percent')
    op.drop_column('duty_calculations', 'anti_dumping_amount')
    op.drop_column('duty_calculations', 'anti_dumping_percent')
    op.drop_column('duty_calculations', 'sws_amount')
    op.drop_column('duty_calculations', 'sws_percent')
    op.drop_column('duty_calculations', 'vat_amount')
    op.drop_column('duty_calculations', 'vat_percent')
    op.drop_column('duty_calculations', 'igst_amount')
    op.drop_column('duty_calculations', 'igst_percent')
    op.drop_column('duty_calculations', 'bcd_amount')
    op.drop_column('duty_calculations', 'bcd_percent')
    op.drop_column('duty_calculations', 'cif_value')
    op.drop_column('duty_calculations', 'port_charge')
    op.drop_column('duty_calculations', 'customs_clearance_fee')
    op.drop_column('duty_calculations', 'incoterm')
    op.drop_column('duty_calculations', 'shipment_mode')
    op.drop_column('duty_calculations', 'destination_country')
    op.drop_column('duty_calculations', 'origin_country')
    # ### end Alembic commands ###
