"""updatedduty 

Revision ID: 5cc2397c7a98
Revises: 447cff61977e
Create Date: 2026-05-22 21:24:55.591487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cc2397c7a98'
down_revision: Union[str, Sequence[str], None] = '447cff61977e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restricted_products')
    op.drop_table('country_master')
    op.drop_table('required_documents')
    op.drop_table('trade_agreements')
    op.drop_table('customs_tax_rules')
    op.add_column('duty_calculations', sa.Column('uploaded_document', sa.Text(), nullable=True))
    op.add_column('duty_calculations', sa.Column('document_uploaded', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duty_calculations', 'document_uploaded')
    op.drop_column('duty_calculations', 'uploaded_document')
    op.create_table('customs_tax_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('basic_custom_duty', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('igst', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('vat', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('social_welfare_surcharge', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('anti_dumping_duty', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('safeguard_duty', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('port_charge', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('customs_handling_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('customs_clearance_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customs_tax_rules_pkey'))
    )
    op.create_table('trade_agreements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('agreement_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reduced_duty', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('exemption_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_agreements_pkey'))
    )
    op.create_table('required_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('product_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('required_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('issuing_authority', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mandatory_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customs_hold_if_missing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('compliance_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('required_documents_pkey'))
    )
    op.create_table('country_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tax_system', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customs_authority', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('default_vat', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sanction_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('country_master_pkey'))
    )
    op.create_table('restricted_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('restriction_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('restriction_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('restriction_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('special_license_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('restricted_authority', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('penalty_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('compliance_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('restricted_products_pkey'))
    )
    # ### end Alembic commands ###
