"""shipment approval system

Revision ID: caf53a518ddc
Revises: 
Create Date: 2026-05-15 11:05:58.918340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf53a518ddc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.alter_column('duty_calculations', 'shipping_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('duty_calculations', 'insurance_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('duty_calculations', 'handling_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.add_column('shipments', sa.Column('approval_status', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('approved_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('shipments', sa.Column('hold_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('shipments', 'hold_reason')
    op.drop_column('shipments', 'approved_at')
    op.drop_column('shipments', 'approved_by')
    op.drop_column('shipments', 'approval_status')
    op.alter_column('duty_calculations', 'handling_fee',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('duty_calculations', 'insurance_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('duty_calculations', 'shipping_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    # ### end Alembic commands ###
