"""updatedduty 

Revision ID: cfd02aabb48e
Revises: 0d5efd692313
Create Date: 2026-05-21 13:01:20.326886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfd02aabb48e'
down_revision: Union[str, Sequence[str], None] = '0d5efd692313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_agreements')
    op.drop_table('customs_tax_rules')
    op.drop_table('required_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('required_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('product_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('required_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('issuing_authority', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mandatory_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customs_hold_if_missing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('compliance_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('required_documents_pkey'))
    )
    op.create_table('customs_tax_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('basic_custom_duty', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('igst', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('vat', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('social_welfare_surcharge', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('anti_dumping_duty', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('safeguard_duty', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('port_charge', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('customs_handling_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('customs_clearance_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customs_tax_rules_pkey'))
    )
    op.create_table('trade_agreements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('agreement_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reduced_duty', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('exemption_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_agreements_pkey'))
    )
    # ### end Alembic commands ###
